name: React.js CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # reuse workflow call
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  merge:
    name: merge main to dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: git merge
      run: |
        git config --global user.email "${GITHUB_ACTOR}"
        git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
        git status
        git pull
        git checkout main
        git status
        git checkout dev
        git status
        git merge -s ort -X theirs --allow-unrelated-histories main
        git push
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'gh-app'
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./gh-app
    - run: |
        npm ci
        npm run build --if-present
        
  deploy:
    name: Deploy site to gh-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Load dependencies
        run: |
          cd gh-app
          npm ci

      - name: Deploy with gh-pages
        run: |
          cd gh-app
          echo start deploy
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}