name: React.js CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # reuse workflow call
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy site to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Load dependencies
        run: |
          cd gh-app
          npm ci

      - name: Deploy with gh-pages
        run: |
          cd gh-app
          echo start deploy
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}